In [1]:
import sys
sys.path.insert(1, '/path/to/application/app/folder')

import Ipynb_importer
import UNdata_country_profile as UNdata
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

importing Jupyter notebook from UNdata_country_profile.ipynb

In [2]:
index_url = "http://data.un.org/en/index.html"
response = requests.get(index_url)
soup = BeautifulSoup(response.content,'lxml')

In [3]:
urls = ["http://data.un.org/en/"+u['href'] for u in soup.section.find_all('a', href=True)]
countries = [c.previousSibling for c in soup.section.find_all("br")]
print(len(urls) == len(countries))

True

In [4]:
total = dict()
for i in range(len(urls)):
    profile = UNdata.get_profile(urls[i])
    total[countries[i]] = profile
    print("Finished:" + countries[i])

Finished:Afghanistan
Finished:Albania
Finished:Algeria
Finished:American Samoa
Finished:Andorra
Finished:Angola
Finished:Anguilla
Finished:Antigua and Barbuda
Finished:Argentina
Finished:Armenia
Finished:Aruba
Finished:Australia
Finished:Austria
Finished:Azerbaijan
Finished:Bahamas
Finished:Bahrain
Finished:Bangladesh
Finished:Barbados
Finished:Belarus
Finished:Belgium
Finished:Belize
Finished:Benin
Finished:Bermuda
Finished:Bhutan
Finished:Bolivia (Plurin. State of)

UNdata_country_profile.ipynb:17: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  "execution_count": 2,

Finished:Bonaire, St. Eustatius & Saba
Finished:Bosnia and Herzegovina
Finished:Botswana
Finished:Brazil
Finished:British Virgin Islands
Finished:Brunei Darussalam
Finished:Bulgaria
Finished:Burkina Faso
Finished:Burundi
Finished:Cabo Verde
Finished:Cambodia
Finished:Cameroon
Finished:Canada
Finished:Cayman Islands
Finished:Central African Republic
Finished:Chad
Finished:Channel Islands
Finished:Chile
Finished:China
Finished:China, Hong Kong SAR
Finished:China, Macao SAR
Finished:Colombia
Finished:Comoros
Finished:Congo
Finished:Cook Islands
Finished:Costa Rica
Finished:Côte d’Ivoire
Finished:Croatia
Finished:Cuba
Finished:Curaçao
Finished:Cyprus
Finished:Czechia
Finished:Dem. People's Rep. Korea
Finished:Dem. Rep. of the Congo
Finished:Denmark
Finished:Djibouti
Finished:Dominica
Finished:Dominican Republic
Finished:Ecuador
Finished:Egypt
Finished:El Salvador
Finished:Equatorial Guinea
Finished:Eritrea
Finished:Estonia
Finished:Eswatini
Finished:Ethiopia
Finished:Falkland Islands (Malvinas)
Finished:Faroe Islands
Finished:Fiji
Finished:Finland
Finished:France
Finished:French Guiana
Finished:French Polynesia
Finished:Gabon
Finished:Gambia
Finished:Georgia
Finished:Germany
Finished:Ghana
Finished:Gibraltar
Finished:Greece
Finished:Greenland
Finished:Grenada
Finished:Guadeloupe
Finished:Guam
Finished:Guatemala
Finished:Guinea
Finished:Guinea-Bissau
Finished:Guyana
Finished:Haiti
Finished:Holy See
Finished:Honduras
Finished:Hungary
Finished:Iceland
Finished:India
Finished:Indonesia
Finished:Iran (Islamic Republic of)
Finished:Iraq
Finished:Ireland
Finished:Isle of Man
Finished:Israel
Finished:Italy
Finished:Jamaica
Finished:Japan
Finished:Jordan
Finished:Kazakhstan
Finished:Kenya
Finished:Kiribati
Finished:Kuwait
Finished:Kyrgyzstan
Finished:Lao People's Dem. Rep.
Finished:Latvia
Finished:Lebanon
Finished:Lesotho
Finished:Liberia
Finished:Libya
Finished:Liechtenstein
Finished:Lithuania
Finished:Luxembourg
Finished:Madagascar
Finished:Malawi
Finished:Malaysia
Finished:Maldives
Finished:Mali
Finished:Malta
Finished:Marshall Islands
Finished:Martinique
Finished:Mauritania
Finished:Mauritius
Finished:Mayotte
Finished:Mexico
Finished:Micronesia (Fed. States of)
Finished:Monaco
Finished:Mongolia
Finished:Montenegro
Finished:Montserrat
Finished:Morocco
Finished:Mozambique
Finished:Myanmar
Finished:Namibia
Finished:Nauru
Finished:Nepal
Finished:Netherlands
Finished:New Caledonia
Finished:New Zealand
Finished:Nicaragua
Finished:Niger
Finished:Nigeria
Finished:Niue
Finished:North Macedonia
Finished:Northern Mariana Islands
Finished:Norway
Finished:Oman
Finished:Pakistan
Finished:Palau
Finished:Panama
Finished:Papua New Guinea
Finished:Paraguay
Finished:Peru
Finished:Philippines
Finished:Poland
Finished:Portugal
Finished:Puerto Rico
Finished:Qatar
Finished:Republic of Korea
Finished:Republic of Moldova
Finished:Réunion
Finished:Romania
Finished:Russian Federation
Finished:Rwanda
Finished:Saint Helena
Finished:Saint Kitts and Nevis
Finished:Saint Lucia
Finished:Saint Pierre and Miquelon
Finished:Saint Vincent & Grenadines
Finished:Samoa
Finished:San Marino
Finished:Sao Tome and Principe
Finished:Saudi Arabia
Finished:Senegal
Finished:Serbia
Finished:Seychelles
Finished:Sierra Leone
Finished:Singapore
Finished:Sint Maarten (Dutch part)
Finished:Slovakia
Finished:Slovenia
Finished:Solomon Islands
Finished:Somalia
Finished:South Africa
Finished:South Sudan
Finished:Spain
Finished:Sri Lanka
Finished:State of Palestine
Finished:Sudan
Finished:Suriname
Finished:Sweden
Finished:Switzerland
Finished:Syrian Arab Republic
Finished:Tajikistan
Finished:Thailand
Finished:Timor-Leste
Finished:Togo
Finished:Tokelau
Finished:Tonga
Finished:Trinidad and Tobago
Finished:Tunisia
Finished:Turkey
Finished:Turkmenistan
Finished:Turks and Caicos Islands
Finished:Tuvalu
Finished:Uganda
Finished:Ukraine
Finished:United Arab Emirates
Finished:United Kingdom
Finished:United Rep. of Tanzania
Finished:United States of America
Finished:United States Virgin Islands
Finished:Uruguay
Finished:Uzbekistan
Finished:Vanuatu
Finished:Venezuela (Boliv. Rep. of)
Finished:Viet Nam
Finished:Wallis and Futuna Islands
Finished:Western Sahara
Finished:Yemen
Finished:Zambia
Finished:Zimbabwe

In [5]:
for c in countries:
    total[c][1] = total[c][1][['Index', 'Unit', 2019]]
    total[c][0].columns = ['Index', c]
    total[c][1].columns = ['Index', 'Unit', c]
    for i in range(len(total[c][0]['Index'].tolist())):
        if total[c][0]['Index'][i] == "Capital city pop.(000,2019)":
            total[c][0]['Index'][i]= "Capital city pop.(000, 2019)"

In [6]:
gi = [total[c][0] for c in countries]
GI = gi[0]
for i in range(len(gi))[1:]:
    GI = pd.merge(GI, gi[i], how="outer", on="Index")

In [7]:
GI

,Index,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,...,Uruguay,Uzbekistan,Vanuatu,Venezuela (Boliv. Rep. of),Viet Nam,Wallis and Futuna Islands,Western Sahara,Yemen,Zambia,Zimbabwe
0,Region,Southern Asia,Southern Europe,Northern Africa,Polynesia,Southern Europe,Middle Africa,Caribbean,Caribbean,South America,...,South America,Central Asia,Melanesia,South America,South-eastern Asia,Polynesia,Northern Africa,Western Asia,Eastern Africa,Eastern Africa
1,"Population(000, 2019)",38042,2881,43053,55,77,31825,15,97,44781,...,3462,32982,300,28516,96462,11,582,29162,17861,14646
2,"Pop. density(per km2, 2019)",58.3,105.1,18.1,276.6,164.1,25.5,165.2,220.7,16.4,...,19.8,77.5,24.6,32.3,311.1,81.7,2.2,55.2,24,37.9
3,Capital city,Kabul,Tirana,Algiers,Pago Pago,Andorra la Vella,Luanda,The Valley,Saint John's,Buenos Aires,...,Montevideo,Tashkent,Port Vila,Caracas,Hanoi,Matu-Utu,El Aaiún,Sana'a,Lusaka,Harare
4,"Capital city pop.(000, 2019)",4114,484.6,2729.3,48.5,22.6,8044.7,1.4,20.8,15057.3,...,1744.7,2490.3,52.7,2935.5,4479.6,1,232.4,2874.4,2646.6,1521.3
5,UN membership date,19-Nov-46,14-Dec-55,8-Oct-62,NaN,28-Jul-93,1-Dec-76,NaN,11-Nov-81,24-Oct-45,...,18-Dec-45,2-Mar-92,15-Sep-81,15-Nov-45,20-Sep-77,NaN,NaN,30-Sep-47,1-Dec-64,25-Aug-80
6,Surface area(km2),652864,28748,2381741,199,468,1246700,91,442,2780400,...,173626,448969,12189,912050,330967,142,266000,527968,752612,390757
7,Sex ratio(m per 100 f),105.5,103.7,102.1,103.6,102.3,97.9,97.6,93.2,95.2,...,93.4,99.5,102.8,97.1,99.7,93.4,109.7,101.5,98.1,91.1
8,National currency,Afghani (AFN),Lek (ALL),Algerian Dinar (DZD),US Dollar (USD),Euro (EUR),Kwanza (AOA),E. Caribbean Dollar (XCD),E. Caribbean Dollar (XCD),Argentine Peso (ARS),...,Peso Uruguayo (UYU),Uzbekistan Sum (UZS),Vatu (VUV),Bolívar (VEF),Dong (VND),CFP Franc (XPF),Moroccan Dirham (MAD),Yemeni Rial (YER),Zambian Kwacha (ZMW),Zimbabwe Dollar (ZWL)
9,Exchange rate(per US$),75,107.8,118.3,NaN,0.9,308.6,2.7,2.7,37.6,...,32.4,8345,112.6,10,22825,104.2,9.6,214.9,11.9,NaN

In [8]:
GI.to_csv("UNdata Country General Information 2019.csv")

In [9]:
ind = [total[c][1] for c in countries]
Ind = ind[0]
for i in range(len(ind))[1:]:
    Ind = pd.merge(Ind, ind[i], how="outer", on= ["Index", "Unit"])

In [10]:
Ind

,Index,Unit,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,...,Uruguay,Uzbekistan,Vanuatu,Venezuela (Boliv. Rep. of),Viet Nam,Wallis and Futuna Islands,Western Sahara,Yemen,Zambia,Zimbabwe
0,GDP: Gross domestic product,(million current US$),21993,13039,167555,NaN,3013,126506,281,1510,...,59180,49677,864,255093,223780,NaN,NaN,27957,25868,18037
1,GDP growth rate,"(annual %, const. 2010 prices)",2.5,3.8,1.4,NaN,1.7,-2.5,-7.7,3,...,2.7,5.2,3.5,-14,6.8,NaN,NaN,-5.9,3.5,3
2,GDP per capita,(current US$),619,4450,4055.2,NaN,39152.8,4247.4,18860.7,14803,...,17120.2,1556.8,3128.4,7977.4,2342.2,NaN,NaN,989.6,1513.3,1091.2
3,Economy: Agriculture,(% of Gross Value Added),23.9,21.7,12.7,NaN,0.6,8.8,2.4,2,...,5.7,19.7,24,5.7,17,NaN,NaN,16.7,4.3,11.6
4,Economy: Industry,(% of Gross Value Added),22,24.2,38.6,NaN,11.4,43.6,11,21.3,...,26.8,34.2,10.4,36.5,37.1,NaN,NaN,25.7,39.9,24.3
5,Economy: Services and other activity,(% of GVA),54.1,54.1,48.6,NaN,88.1,47.5,86.6,76.8,...,67.5,46.2,65.5,57.8,45.8,NaN,NaN,57.6,55.8,64.1
6,Employment: Agriculture,(% of employed),61.7,37.8,12.6,...,NaN,50,...,...,...,7.8,20.7,64.5,9.7,38.4,NaN,30.1,41.5,52.5,68.7
7,Employment: Industry,(% of employed),6.8,18.8,46.7,...,NaN,8.7,...,...,...,19.8,37.7,5.9,23.7,25.4,NaN,31,13.4,12.1,7.3
8,Employment: Services,(% employed),31.5,43.4,40.7,...,NaN,41.2,...,...,...,72.4,41.6,29.6,66.6,36.2,NaN,38.9,45,35.4,24
9,Unemployment,(% of labour force),8.8,15.1,9.9,...,NaN,8.9,...,...,...,8.2,6.7,5.2,7.7,2.1,NaN,7.2,14,7.8,5
10,Labour force participation,(female/male pop. %),48.8/82.1,47.1/64.8,14.9/67.2,... / ...,NaN,75.4/80.0,... / ...,... / ...,...,55.9/73.8,53.4/78.0,61.5/79.7,47.8/76.9,72.5/82.3,NaN,27.4/79.7,5.8/70.9,70.8/79.7,78.7/89.0
11,CPI: Consumer Price Index,(2010=100),145,117,148,NaN,106,337,106,112,...,188,NaN,108,772,161,NaN,NaN,158,195,106
12,Agricultural production index,(2004-2006=100),125,143,151,116,NaN,192,NaN,70,...,118,167,124,109,138,112,107,141,183,100
13,International trade: Exports,(million current US$),822,2876,41347,NaN,129,38953,5,46,...,9148,14258,63,6614,247989,1,NaN,16569,9052,4037
14,International trade: Imports,(million current US$),8345,5942,49214,NaN,1623,18019,283,829,...,9381,19557,355,2667,266122,60,NaN,15493,9462,6259
15,International trade: Balance,(million current US$),- 7 523,- 3 066,- 7 867,NaN,- 1 494,20935,-278,-783,...,-233,- 5 300,-291,3947,- 18 133,-59,NaN,1076,-410,- 2 222
16,"Balance of payments, current account",(million US$),- 4 227,- 1 008,- 22 059,NaN,NaN,7502,-62,34,...,-374,- 3 577,-82,- 3 870,6124,NaN,NaN,- 2 419,-342,-308
17,Population growth rate,(average annual %),3.3,-0.4,2,-~0.0,-1.6,3.5,1.2,1.2,...,0.3,1.6,2.8,1.1,1,-2.1,1.8,2.7,3.1,1.7
18,Urban population,(% of total population),25.8,61.2,73.2,87.1,88,66.2,100,24.5,...,95.4,50.4,25.4,88.2,36.6,0,86.8,37.3,44.1,32.2
19,Urban population growth rate,(average annual %),4,1.8,2.9,-0.1,-1.7,4.7,1.2,0.1,...,0.5,1.5,2.7,1.4,3.2,0,1.9,4.4,4.3,1.8
20,"Fertility rate, total",(live births per woman),5.4,1.7,3,2.6,1.2,6,...,2,...,2,2.4,4,2.4,2,2.1,2.6,4.4,5.2,4.1
21,Life expectancy at birth,"(females/males, years)",63.8/60.9,80.0/75.2,76.7/74.4,77.8/71.1,NaN,60.5/55.2,... / ...,77.4/74.8,...,80.7/73.2,72.7/67.8,71.2/68.0,77.0/69.4,79.1/70.8,78.7/72.8,70.3/66.9,67.7/64.3,61.5/57.0,58.3/54.9
22,Population age distribution,"(0-14/60+ years old, %)",42.5/4.2,17.4/20.5,30.6/9.7,33.3/9.0,14.4/19.0,46.6/3.6,23.3/7.6,22.0/13.6,...,20.5/20.0,28.8/8.0,38.7/5.8,27.4/11.6,23.2/11.9,25.5/15.4,27.4/6.0,39.2/4.6,44.5/3.4,42.2/4.6
23,International migrant stock,(000/% of total pop.),133.6/0.4,52.5/1.8,248.6/0.6,23.6/42.3,41.0/53.3,638.5/2.1,5.6/37.4,28.6/28.1,...,79.6/2.3,1159.2/3.6,3.2/1.2,1426.3/4.5,76.1/0.1,2.8/23.6,5.4/1.0,384.3/1.4,157.0/0.9,403.9/2.4
24,Refugees and others of concern to UNHCR,(000),2537.1,4,185.8,NaN,NaN,68.1,~0.0,~0.0,...,10.5,85.5,~0.0,123.5,29.5,NaN,NaN,2405.7,73.1,19.8
25,Infant mortality rate,(per 1 000 live births),60.1,9.2,24.9,9.6,NaN,78.2,NaN,6.8,...,10,27.7,24.3,15,17.9,...,34.1,43.3,53.3,51.2
26,Health: Current expenditure,(% of GDP),10.2,6.7,6.6,NaN,10.4,2.9,NaN,4.3,...,9.1,6.3,3.7,3.2,5.7,NaN,NaN,5.6,4.5,9.4
27,Health: Physicians,(per 1 000 pop.),0.3,1.2,1.8,NaN,3.3,0.2,NaN,2.8,...,5,2.4,0.2,...,0.8,NaN,NaN,0.3,0.1,0.1
28,Education: Government expenditure,(% of GDP),3.9,4,...,...,3.2,...,...,...,...,4.4,6.4,4.7,...,5.7,NaN,NaN,...,...,7.5
29,Education: Primary gross enrol. ratio,(f/m per 100 pop.),84.2/122.7,108.6/111.5,108.8/114.5,NaN,NaN,105.2/121.6,NaN,86.1/89.2,...,104.3/106.6,102.3/103.9,118.7/120.7,92.1/94.6,108.2/107.7,NaN,NaN,86.1/98.6,100.9/98.7,97.9/99.5
30,Education: Secondary gross enrol. ratio,(f/m per 100 pop.),39.6/69.1,93.1/99.0,101.5/97.8,NaN,NaN,39.3/62.0,NaN,90.6/94.4,...,... / ...,92.4/93.6,56.4/53.4,87.2/80.9,NaN,NaN,NaN,42.8/58.9,NaN,46.7/47.6
31,Education: Tertiary gross enrol. ratio,(f/m per 100 pop.),3.6/14.6,70.8/44.4,57.3/38.5,NaN,NaN,8.5/10.4,NaN,29.2/14.1,...,... / ...,6.9/11.3,... / ...,... / ...,31.3/25.3,NaN,NaN,6.1/13.7,3.5/4.6,8.0/8.9
32,Intentional homicide rate,(per 100 000 pop.),6.3,2.7,1.4,5.4,1.2,4.8,27.7,10.3,...,7.7,...,2.1,56.3,1.5,NaN,NaN,6.7,5.3,6.7
33,Seats held by women in national parliaments,(%),27.7,29.3,25.8,NaN,32.1,30,NaN,11.1,...,22.2,16,0,22.2,26.7,NaN,NaN,0.3,18,31.8
34,Individuals using the Internet,(per 100 inhabitants),11.4,71.8,47.7,NaN,98.9,14.3,81.6,76,...,68.3,52.3,25.7,64.3,49.6,9,NaN,26.7,27.9,27.1
35,Threatened species,(number),40,136,143,95,14,158,57,59,...,110,62,140,345,694,89,50,308,94,103
36,Forested area,(% of land area),2.1,28.1,0.8,87.5,34,46.3,61.1,22.3,...,10.7,7.5,36.1,52.7,48.1,41.6,2.7,1,65.2,35.5
37,CO2 emission estimates,(million tons/tons per capita),9.8/0.3,5.7/2.0,145.4/3.7,NaN,0.5/6.4,34.8/1.4,0.1/9.8,0.5/5.8,...,6.7/2.0,105.2/3.6,0.2/0.6,185.2/6.1,166.9/1.8,~0.0 / 1.6,NaN,22.7/0.9,4.5/0.3,12.0/0.8
38,"Energy production, primary",(Petajoules),70,82,6283,NaN,1,4101,0,0,...,126,2134,1,6751,2880,NaN,NaN,65,417,380
39,Energy supply per capita,(Gigajoules),4,31,54,NaN,116,23,149,79,...,62,50,11,73,32,30,NaN,5,28,29
40,Important sites for terrestrial biodiversity p...,(%),6.1,67,38.8,61.5,26.1,28.4,0.2,18.4,...,20.8,15.9,6.4,67.4,40.9,0,NaN,31.1,48.3,85.9
41,Net Official Development Assist. received,(% of GNI),18.1,1.2,0.11,NaN,NaN,0.19,NaN,0.66,...,0.08,1.26,15.48,0.01,1.12,NaN,NaN,8.47,4.14,4.6
42,Index of industrial production,(2005=100),NaN,355,104,NaN,NaN,NaN,NaN,NaN,...,NaN,175,NaN,NaN,199,NaN,NaN,NaN,157,NaN
43,Research & Development expenditure,(% of GDP),NaN,...,...,...,NaN,NaN,NaN,NaN,...,0.4,0.2,NaN,0.2,0.4,NaN,NaN,NaN,...,NaN
44,Tourist/visitor arrivals at national borders,(000),NaN,4643,2451,20,3003,261,68,247,...,3674,2690,109,427,12922,NaN,NaN,367,1083,2423
45,Net Official Development Assist. disbursed,(% of GNI),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
Ind.to_csv("UNdata Country Indicators 2019.csv")